import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://app-boomerang-keycloak-dev-001.azurewebsites.net/realms/Boomerang-Test/protocol/openid-connect/auth?client_id=boomerang-test&scope=openid%20email%20profile%20offline_access&response_type=code&redirect_uri=https%3A%2F%2Fapp-boomerang-web-test-001.azurewebsites.net%2Fapi%2Fauth%2Fcallback%2Fkeycloak&state=SvwbhFhRhLH3Uzyzcp6dwl1kWJsCqSv165Iug2sTjmc&code_challenge=u62OyNc0Ik4BI3gk-68TgWAgobv5ofFGd1K88_c0LIk&code_challenge_method=S256');
  await page.getByRole('textbox', { name: 'Username or email' }).click();
  await page.getByRole('textbox', { name: 'Username or email' }).fill('testautomation@gmail.com');
  await page.getByRole('textbox', { name: 'Username or email' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('12345');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('a').filter({ hasText: 'Feedback Requests' }).click();
  await page.goto('https://app-boomerang-web-test-001.azurewebsites.net/performance-appraisals/feedback-requests?pagination=%7B%22pageIndex%22%3A0%2C%22pageSize%22%3A15%7D&sorting=%5B%7B%22id%22%3A%22createdTime%22%2C%22desc%22%3Atrue%7D%5D&columnVisibility=%7B%22updatedTime%22%3Afalse%7D&status=active');
  await page.getByRole('cell', { name: 'Appraisal for Test Automation' }).nth(1).click();
  //Form filling
  await expect(page.getByRole('heading', { name: 'Skill Assessments' })).toBeVisible();
  await page.locator('[id=":rk:-form-item"]').getByRole('button', { name: 'Rate 1 out of' }).click();
  await page.locator('[id=":rl:-form-item"]').getByRole('button', { name: 'Rate 2 out of' }).click();
  await page.locator('[id=":rm:-form-item"]').getByRole('button', { name: 'Rate 3 out of' }).click();
  await page.locator('[id=":rn:-form-item"]').getByRole('button', { name: 'Rate 4 out of' }).click();
  await page.locator('[id=":rn:-form-item"]').getByRole('button', { name: 'Rate 4 out of' }).click();
  await page.locator('[id=":ro:-form-item"]').getByRole('button', { name: 'Rate 5 out of' }).click();
  await page.locator('[id=":rp:-form-item"]').getByRole('button', { name: 'Rate 4 out of' }).click();
  await page.locator('[id=":rq:-form-item"]').getByRole('button', { name: 'Rate 4 out of' }).click();
  await page.locator('[id=":rr:-form-item"]').getByRole('button', { name: 'Rate 4 out of' }).click();
  await page.locator('[id=":rs:-form-item"]').getByRole('button', { name: 'Rate 5 out of' }).click();
  await page.locator('[id=":rt:-form-item"]').click();
  await page.locator('[id=":rt:-form-item"]').fill('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vitae turpis aliquam, imperdiet felis ac, euismod nunc. Mauris ac nisl fermentum, rhoncus ligula eget, tristique libero. Nunc hendrerit sit amet nisi in luctus. Duis ut venenatis purus. Donec euismod dignissim odio non tempor. Proin vitae dui lacus. Cras tempor massa ac ex rutrum, a semper arcu rutrum. Suspendisse vestibulum enim quis convallis tincidunt. Nunc lobortis molestie pretium. Praesent non interdum arcu. Sed vulputate tortor suscipit, placerat magna nec, malesuada nulla. Ut vel dui rhoncus, lacinia magna a, euismod augue.');
  await page.locator('[id=":ru:-form-item"]').getByRole('button', { name: 'Rate 2 out of' }).click();
  await page.locator('[id=":rv:-form-item"]').getByRole('button', { name: 'Rate 2 out of' }).click();
  await page.locator('[id=":r10:-form-item"] > div > .justify-around.grid > button:nth-child(2)').click();
  await page.locator('textarea[name="categories.1.comment"]').click();
  await page.locator('textarea[name="categories.1.comment"]').fill('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vitae turpis aliquam, imperdiet felis ac, euismod nunc. Mauris ac nisl fermentum, rhoncus ligula eget, tristique libero. Nunc hendrerit sit amet nisi in luctus. Duis ut venenatis purus. Donec euismod dignissim odio non tempor. Proin vitae dui lacus. Cras tempor massa ac ex rutrum, a semper arcu rutrum. Suspendisse vestibulum enim quis convallis tincidunt. Nunc lobortis molestie pretium. Praesent non interdum arcu. Sed vulputate tortor suscipit, placerat magna nec, malesuada nulla. Ut vel dui rhoncus, lacinia magna a, euismod augue.');
  await page.locator('[id=":r10:-form-item"] > div > .justify-around.grid > button:nth-child(3)').click();
  await page.locator('[id=":r12:-form-item"] > div > .justify-around.grid > button:nth-child(2)').click();
  await page.locator('[id=":r13:-form-item"] > div > .justify-around.grid > button:nth-child(3)').click();
  await page.locator('[id=":r14:-form-item"] > div > .justify-around.grid > button:nth-child(4)').click();
  await page.locator('textarea[name="categories.2.comment"]').click();
  await page.locator('textarea[name="categories.2.comment"]').fill('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vitae turpis aliquam, imperdiet felis ac, euismod nunc. Mauris ac nisl fermentum, rhoncus ligula eget, tristique libero. Nunc hendrerit sit amet nisi in luctus. Duis ut venenatis purus. Donec euismod dignissim odio non tempor. Proin vitae dui lacus. Cras tempor massa ac ex rutrum, a semper arcu rutrum. Suspendisse vestibulum enim quis convallis tincidunt. Nunc lobortis molestie pretium. Praesent non interdum arcu. Sed vulputate tortor suscipit, placerat magna nec, malesuada nulla. Ut vel dui rhoncus, lacinia magna a, euismod augue.');
  await page.locator('[id=":r16:-form-item"] > div > .justify-around.grid > button:nth-child(4)').click();
  await page.locator('[id=":r17:-form-item"] > div > .justify-around.grid > button:nth-child(4)').click();
  await page.locator('textarea[name="categories.3.comment"]').click();
  await page.locator('textarea[name="categories.3.comment"]').fill('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vitae turpis aliquam, imperdiet felis ac, euismod nunc. Mauris ac nisl fermentum, rhoncus ligula eget, tristique libero. Nunc hendrerit sit amet nisi in luctus. Duis ut venenatis purus. Donec euismod dignissim odio non tempor. Proin vitae dui lacus. Cras tempor massa ac ex rutrum, a semper arcu rutrum. Suspendisse vestibulum enim quis convallis tincidunt. Nunc lobortis molestie pretium. Praesent non interdum arcu. Sed vulputate tortor suscipit, placerat magna nec, malesuada nulla. Ut vel dui rhoncus, lacinia magna a, euismod augue.');
  await page.locator('[id=":r19:-form-item"] > div > .justify-around.grid > button:nth-child(5)').click();
  await page.locator('[id=":r1a:-form-item"] > div > .justify-around.grid > button:nth-child(5)').click();
  await page.locator('[id=":r1b:-form-item"] > div > .justify-around.grid > button:nth-child(5)').click();
  await page.locator('[id=":r1b:-form-item"] > div > .justify-around.grid > button:nth-child(5)').click();
  await page.locator('textarea[name="categories.4.comment"]').click();
  await page.locator('textarea[name="categories.4.comment"]').fill('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vitae turpis aliquam, imperdiet felis ac, euismod nunc. Mauris ac nisl fermentum, rhoncus ligula eget, tristique libero. Nunc hendrerit sit amet nisi in luctus. Duis ut venenatis purus. Donec euismod dignissim odio non tempor. Proin vitae dui lacus. Cras tempor massa ac ex rutrum, a semper arcu rutrum. Suspendisse vestibulum enim quis convallis tincidunt. Nunc lobortis molestie pretium. Praesent non interdum arcu. Sed vulputate tortor suscipit, placerat magna nec, malesuada nulla. Ut vel dui rhoncus, lacinia magna a, euismod augue.');
  await page.locator('[id=":r1d:-form-item"] > div > .justify-around.grid > button:nth-child(4)').click();
  await page.locator('textarea[name="categories.5.comment"]').click();
  await page.locator('textarea[name="categories.5.comment"]').fill('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vitae turpis aliquam, imperdiet felis ac, euismod nunc. Mauris ac nisl fermentum, rhoncus ligula eget, tristique libero. Nunc hendrerit sit amet nisi in luctus. Duis ut venenatis purus. Donec euismod dignissim odio non tempor. Proin vitae dui lacus. Cras tempor massa ac ex rutrum, a semper arcu rutrum. Suspendisse vestibulum enim quis convallis tincidunt. Nunc lobortis molestie pretium. Praesent non interdum arcu. Sed vulputate tortor suscipit, placerat magna nec, malesuada nulla. Ut vel dui rhoncus, lacinia magna a, euismod augue.');
  await page.locator('textarea[name="questions.0.value"]').click();
  await page.locator('textarea[name="questions.0.value"]').fill('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vitae turpis aliquam, imperdiet felis ac, euismod nunc. Mauris ac nisl fermentum, rhoncus ligula eget, tristique libero. Nunc hendrerit sit amet nisi in luctus. Duis ut venenatis purus. Donec euismod dignissim odio non tempor. Proin vitae dui lacus. Cras tempor massa ac ex rutrum, a semper arcu rutrum. Suspendisse vestibulum enim quis convallis tincidunt. Nunc lobortis molestie pretium. Praesent non interdum arcu. Sed vulputate tortor suscipit, placerat magna nec, malesuada nulla. Ut vel dui rhoncus, lacinia magna a, euismod augue.');
  await page.locator('textarea[name="questions.1.value"]').click();
  await page.locator('textarea[name="questions.1.value"]').fill('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vitae turpis aliquam, imperdiet felis ac, euismod nunc. Mauris ac nisl fermentum, rhoncus ligula eget, tristique libero. Nunc hendrerit sit amet nisi in luctus. Duis ut venenatis purus. Donec euismod dignissim odio non tempor. Proin vitae dui lacus. Cras tempor massa ac ex rutrum, a semper arcu rutrum. Suspendisse vestibulum enim quis convallis tincidunt. Nunc lobortis molestie pretium. Praesent non interdum arcu. Sed vulputate tortor suscipit, placerat magna nec, malesuada nulla. Ut vel dui rhoncus, lacinia magna a, euismod augue.');
  await page.locator('textarea[name="overallComment"]').click();
  await page.locator('textarea[name="overallComment"]').fill('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vitae turpis aliquam, imperdiet felis ac, euismod nunc. Mauris ac nisl fermentum, rhoncus ligula eget, tristique libero. Nunc hendrerit sit amet nisi in luctus. Duis ut venenatis purus. Donec euismod dignissim odio non tempor. Proin vitae dui lacus. Cras tempor massa ac ex rutrum, a semper arcu rutrum. Suspendisse vestibulum enim quis convallis tincidunt. Nunc lobortis molestie pretium. Praesent non interdum arcu. Sed vulputate tortor suscipit, placerat magna nec, malesuada nulla. Ut vel dui rhoncus, lacinia magna a, euismod augue.');
  await page.getByRole('button', { name: 'Save as draft' }).click();
});